import Navigation from "../components/navigation"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <link href="https://hangeul.pstatic.net/hangeul_static/css/maru-buri.css" rel="stylesheet"></link>
      <style> { `body { font-family: 'MaruBuri'; }`} </style>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
